import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "24K金项链",
    description: "精致的24K金项链，适合各种场合佩戴，展现高贵气质。",
    price: 3999.99,
    stock: 10,
    category: "necklaces",
    featured: true,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
  },
  {
    id: "2",
    name: "18K金戒指",
    description: "精美的18K金戒指，简约设计，适合日常佩戴。",
    price: 2499.99,
    stock: 15,
    category: "rings",
    featured: true,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
  },
  {
    id: "3",
    name: "足金手镯",
    description: "传统足金手镯，纯手工打造，适合送礼或自用。",
    price: 5999.99,
    stock: 5,
    category: "bracelets",
    featured: true,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
  },
  {
    id: "4",
    name: "玫瑰金项链",
    description: "时尚玫瑰金项链，适合年轻人佩戴，展现活力与时尚。",
    price: 1999.99,
    stock: 20,
    category: "necklaces",
    featured: false,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
  },
  {
    id: "5",
    name: "钻石戒指",
    description: "精致钻石戒指，适合求婚或纪念日礼物。",
    price: 9999.99,
    stock: 3,
    category: "rings",
    featured: true,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
  },
  {
    id: "6",
    name: "黄金手链",
    description: "轻巧黄金手链，适合日常佩戴，展现优雅气质。",
    price: 1599.99,
    stock: 0,
    category: "bracelets",
    featured: false,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
  },
  {
    id: "7",
    name: "白金项链",
    description: "高贵白金项链，简约设计，适合各种场合佩戴。",
    price: 4599.99,
    stock: 8,
    category: "necklaces",
    featured: false,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
  },
  {
    id: "8",
    name: "金镶玉戒指",
    description: "传统金镶玉戒指，结合中国传统文化元素，独特而精美。",
    price: 3299.99,
    stock: 7,
    category: "rings",
    featured: false,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
  },
]

